# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json pnpm-lock.yaml tsconfig.json ./
RUN npm install -g pnpm && pnpm install
COPY src ./src
RUN pnpm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies
COPY package.json pnpm-lock.yaml ./
# Copy node_modules from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build

# Set entrypoint for stdio MCP server
ENTRYPOINT ["node", "build/index.js"]
