import type { paths, components } from "./api-types.js";

// Root aliases for the generated OpenAPI types. Keep these in a single place
// so tools and formatters can import them without depending directly on the
// autogenerated file.
export type Paths = paths;
export type Components = components;

/**
 * Helper type for extracting typed JSON responses from the OpenAPI-generated
 * `paths` definition. Given a path, HTTP method, and optional status code,
 * this resolves to the corresponding `application/json` response body.
 *
 * Pattern for new endpoints:
 *   type MyEndpointResponse = ApiResponse<\"/my-path\", \"get\" | \"post\">;
 *
 * Example:
 *   type ListSdkConnectionsResponse = ApiResponse<\"/sdk-connections\", \"get\">;
 *
 * Note: We intentionally keep the constraint surface narrow here and rely on
 * the concrete aliases (e.g. `ListSdkConnectionsResponse`) so we don't have
 * to model the full `operations` generic structure from openapi-typescript.
 */
export type ApiResponse<
  TPath extends keyof Paths,
  TMethod extends keyof Paths[TPath],
  // Status code is left unconstrained; aliases should specify a concrete code.
  TStatus extends number = 200
> = any;

// SDK Connections
export type ListSdkConnectionsResponse =
  Paths["/sdk-connections"]["get"]["responses"][200]["content"]["application/json"];
export type CreateSdkConnectionResponse =
  Paths["/sdk-connections"]["post"]["responses"][200]["content"]["application/json"];

// Features
export type ListFeaturesResponse =
  Paths["/features"]["get"]["responses"][200]["content"]["application/json"];
export type CreateFeatureResponse =
  Paths["/features"]["post"]["responses"][200]["content"]["application/json"];
export type GetFeatureResponse =
  Paths["/features/{id}"]["get"]["responses"][200]["content"]["application/json"];
export type UpdateFeatureResponse =
  Paths["/features/{id}"]["post"]["responses"][200]["content"]["application/json"];
export type DeleteFeatureResponse =
  Paths["/features/{id}"]["delete"]["responses"][200]["content"]["application/json"];
export type ToggleFeatureResponse =
  Paths["/features/{id}/toggle"]["post"]["responses"][200]["content"]["application/json"];

// Projects
export type ListProjectsResponse =
  Paths["/projects"]["get"]["responses"][200]["content"]["application/json"];

// Environments
export type ListEnvironmentsResponse =
  Paths["/environments"]["get"]["responses"][200]["content"]["application/json"];

// Attributes
export type ListAttributesResponse =
  Paths["/attributes"]["get"]["responses"][200]["content"]["application/json"];

// Experiments
export type ListExperimentsResponse =
  Paths["/experiments"]["get"]["responses"][200]["content"]["application/json"];
export type GetExperimentResponse =
  Paths["/experiments/{id}"]["get"]["responses"][200]["content"]["application/json"];
export type PostExperimentResponse =
  Paths["/experiments"]["post"]["responses"][200]["content"]["application/json"];
export type GetExperimentResultsResponse =
  Paths["/experiments/{id}/results"]["get"]["responses"][200]["content"]["application/json"];

// Metrics
export type ListMetricsResponse =
  Paths["/metrics"]["get"]["responses"][200]["content"]["application/json"];
export type GetMetricResponse =
  Paths["/metrics/{id}"]["get"]["responses"][200]["content"]["application/json"];
export type ListFactMetricsResponse =
  Paths["/fact-metrics"]["get"]["responses"][200]["content"]["application/json"];
export type GetFactMetricResponse =
  Paths["/fact-metrics/{id}"]["get"]["responses"][200]["content"]["application/json"];

// Stale features
export type GetStaleFeatureResponse =
  Paths["/stale-features"]["get"]["responses"][200]["content"]["application/json"];

// Data sources (used by defaults)
export type ListDataSourcesResponse =
  Paths["/data-sources"]["get"]["responses"][200]["content"]["application/json"];

// Component schema aliases (for formatters that work with single entities or arrays)
export type Feature = Components["schemas"]["Feature"];
